<a href="https://colab.research.google.com/github/a-forty-two/EY_24Feb25_batch10/blob/main/24Feb_001_IntroToDataStructures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# scalar value , 0-rank Tensor or 0-dimension
a =1
b = 'hello world'
c = 3.15
d = True

In [2]:
# Vector , 1-rank tensor
blahblah = [1, 2, 3, 4, 5, 6]

In [3]:
# Matrix , 2-rank tensors
matrix = [[1, 2, 3],
 [4, 5, 6],
  [7, 8, 9]]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [5]:
# cube, 3-D, 3-rank tensors

cube = [ [ [1,2], [2,1]]]

In [8]:
# N-dimension TENSORS

data = [[[[[[1,2]]]]]]
data

[[[[[[1, 2]]]]]]

In [9]:
# reshaping functions -> allow us to convert one dimension type to another
import numpy as np

data1 = [1,2,3,4,5,6,7,8]

data2 = np.reshape(data1, (1,8))
data3 = np.reshape(data1, (8,1))
data4 = np.reshape(data1, (2,4))
data5 = np.reshape(data1, (4,2))


In [10]:
data2

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [11]:
data3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [12]:
data4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
data5

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
data6 = np.reshape(data1, (2,2,2))
data6

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
data7 = np.reshape(data1, (1,1,1,1,1,1,2,2,2,1))
data7

array([[[[[[[[[[1],
               [2]],

              [[3],
               [4]]],


             [[[5],
               [6]],

              [[7],
               [8]]]]]]]]]])

In [16]:
data7.shape

(1, 1, 1, 1, 1, 1, 2, 2, 2, 1)

In [19]:

# Array is known as LIST in python
# List is a 1-D structure

mylist = [ 0.0, "hello", 42, False, True, 1, 0.55]

print(mylist)

[0.0, 'hello', 42, False, True, 1, 0.55]


In [20]:

# INDEXED, ORDERED, MUTABLE Collection -> it will carry an index, and the
# positions will never change

#ordered -> sequence of elements will never change

# mutable -> make ANY changes to any of the values!


# indexing
# left to right-> 0 to positive
# right to left -> negative numbers
print(mylist[0]) # first element

print(mylist[-1]) # last element

0.0
0.55


In [21]:
a = [1,2]
b = [2,1]
c = [a,b]
print(c)

[[1, 2], [2, 1]]


In [22]:
#mutable
mylist[0] = 'bye bye'

In [24]:
# TUPLES -> ORDERED, INDEXED, IMMUTABLE

# Once created NO MORE CHANGES!!!
mytuple = (0.0, "hello", 42, False, True, 1, 0.55)
print(mytuple[-1]) # indexed
print(mytuple) # ORDERED

0.55
(0.0, 'hello', 42, False, True, 1, 0.55)


In [25]:
# IMMUTABLE-> error expected
mytuple[-1] = 'hello world'

TypeError: 'tuple' object does not support item assignment

In [26]:
# SET -> NO DUPLICATES, UNORDERED, UNINDEXED

a1 = { 'apple', 'banana', 'apple'}
a2 = { 'banana', 'apple'}
print(a1)
print(a2)

{'banana', 'apple'}
{'banana', 'apple'}


In [27]:
print(a1-a2)

set()


In [28]:
# UNINDEXED -> Error expected
a1[0]

TypeError: 'set' object is not subscriptable

In [36]:
# UNORDERED, UNINDEXED
s1 = { 'apple', 42, False, 0, 1, True, 'blah'}
s2 = { 0, 1, True, 'blah'}
print(s1)
print(s2)


{False, 1, 'apple', 42, 'blah'}
{0, 1, 'blah'}


In [29]:
# list [ ]
# set { }
# tuple ( )


In [33]:
# DICTIONARY -> Key,value pairs!
# UNORDERED, INDEXED, MUTABLE collection
# special SET where we also have INDEXES -> KEYS!
# Keys need to be unique

mydict = { -1: 'world', 42:False, 'pi':3.14}

In [31]:
# INDEXING is NOT 0...Positive numbers, but only the KEYS
# defined the dictionary!

print(mydict[0]) # ERROR -> no key called 0 present

KeyError: 0

In [32]:
print(mydict['pi'])

3.14


In [35]:
for key,value in mydict.items():
  print(key, value)

-1 world
42 False
pi 42
